### ISSUE TITLE
Module imports

### ISSUE THREAD

**Issue by akovari** [abzu-lang/abzu#1]
This feature allows importing and using modules.

Syntax
-------
Calling a function from a module:

    package.Module.function arg1 arg2

Functionality
--------------

    let Module = package.Module in <expr>

Behaviour
-----------
Module call syntax locates the module from the cache or file system location, makes sure it's parsed and cached.

Module call syntax is to be extended in the future to allow reading a library manifest file (to be defined) and import module from specified library version/location.

**Comment by kurobako** [comment]
can we make import function implicit and free the keyword?
for ex. `let Module = package.Module in <expr>`

**Comment by akovari** [comment]
Yes, I was just thinking that too.

**Comment by akovari** [comment]
Implemented by 7ee946abe410063b2ebcb5f3461a0223d5fcff72, though without caching yet. #5 is specifically for that.
